local lstemcell = {
	name                = [[Locust Nanomorph]],
	description         = [[The basic unit of Locust self-replication. Can morph into many other Locust units]],
    acceleration        = 0.06,
    brakerate           = 1.5,
    buildpic            = [[kairdrone.png]],
	buildCostEnergy     = 200,
	buildCostMetal      = 200,
    buildDistance       = 150,
    builder             = false,
	buildTime           = 15,
    canAssist           = false,
	CanAttack 			= 0,
	CanCapture			= 0,
    canGuard            = false,
	canMove		  	    = false,
	canPatrol           = false,
    canReclaim          = false,
	canStop             = true,
	category            = [[LAND]],
    canFly              = false,
	collide             = true,
	corpse              = [[DEAD]],
    cruiseAlt           = 400,
	
	cloakCost           = 10,
    cloakCostMoving     = 10,
    init_Cloaked        = false,
	
	reclaimable         = false,
	stealth             = false,
    energyMake          = 1,
	explodeAs           = [[DRONE_GROUND_UNIT]],
    footprintx          = 2,
	footprintZ          = 2,
	hoverAttack         = false,
	idleAutoHeal        = 1,
	leaveTracks         = false,
	mass                = 80,
	maxDamage           = 500,
    maxSlope            = 99999999,
	maxVelocity         = 0,
    maxWaterDepth       = 10000,
    metalMake           = 0,
	minCloakDistance    = 75,
    noChaseCategory     = [[MINERALS LAND SINK HOVER SHIP FLOAT SUB]],
	objectName          = "kairdrone.s3o",
    onoffable           = false,
    seismicSignature    = 4,
    selfDestructAs      = [[DRONE_GROUND_UNIT]],
    side                = [[Drone]],
    sightDistance       = 350,
	sounds			= {
	      select = {
		"golgotha/vehicle_done_44khz",
		},
	      ok = {
		"golgotha/vehicle_done_44khz",
		},
	  },
	  
	smoothAnim          = true,
	turnInPlace         = 1,
	turnRate            = 00,
	showNanospray	    = 1,
	Resurrectspeed      = 100,
	workerTime          = 1,
	script              = "lstemcell.lua",

	featureDefs         = {
	
	    DEAD = {
	      description      = [[Debris - Air Drone]],
	      blocking         = false,
	      category         = [[heaps]],
	      damage           = 125,
	      energy           = 0,
	      footprintX       = 2,
	      footprintZ       = 2,
	      metal            = 25,
	      object           = [[b2x2heap.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 750,
	    },

  	  },

	}


return lowerkeys({ ["lstemcell"] = lstemcell })
